name: ci

on:
  push:
    branches: 
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Logs / All tags & variables
        run: |
          echo "::set-env name=DOCKER_TAG::$(cat tag)"

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.TUXEDOSECOM_DOCKER_HUB_USER }}
          password: ${{ secrets.TUXEDOSECOM_DOCKER_HUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            tuxedosecom/openvpn:$DOCKER_TAG
            tuxedosecom/openvpn:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
